# This is a basic workflow to help you get started with Actions

name: Test Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: generate build path
      run: echo "::set-output name=build::${{github.event.number}}/$(date +'%Y-%m-%dT%H:%M:%S')/"
      id: build-path

    - name: print build path
      run: echo "Build path is ${{ steps.build-path.outputs.build }}"
